# Install pre-built Media MCP Server package (no compilation)
param(
    [string]$TargetDir = "",
    [ValidateSet('cursor', 'claude', 'codex', 'antigravity', 'windsurf', 'snippets', 'print', 'all')]
    [string]$Mode = 'all',
    [string]$ServerName = 'media-mcp-server'
)

$ErrorActionPreference = "Stop"

# Package root = directory containing this install.ps1
$PkgRoot = if ($TargetDir) { (Resolve-Path $TargetDir).Path } else { $PSScriptRoot }
$BinDir = Join-Path $PkgRoot 'bin'
$ExePath = Join-Path $BinDir 'MediaMCPServer.exe'
$MediaDir = Join-Path $PkgRoot 'data\media'
$ConfigDir = Join-Path $PkgRoot 'config'

function Test-Package {
    $missing = @()
    foreach ($f in @('MediaMCPServer.exe', 'opencv_delphi_wrapper.dll')) {
        if (-not (Test-Path (Join-Path $BinDir $f))) { $missing += $f }
    }
    if ($missing.Count -gt 0) {
        throw "Invalid package - missing in bin\: $($missing -join ', ')"
    }
}

function New-McpJson([string]$Exe, [string]$Cwd) {
    @{
        mcpServers = @{
            $ServerName = @{
                command = $Exe
                args = @()
                cwd = $Cwd
            }
        }
    } | ConvertTo-Json -Depth 5
}

function New-CodexToml([string]$Exe, [string]$Cwd) {
    $exePath = $Exe -replace '\\', '/'
    $cwdPath = $Cwd -replace '\\', '/'
    $dataPath = (Join-Path $PkgRoot 'data\media') -replace '\\', '/'
    @"
# Media MCP Server - generated by install.ps1
# Merge into %USERPROFILE%\.codex\config.toml or use .codex\config.toml in project root

[mcp_servers.$ServerName]
command = "$exePath"
args = []
cwd = "$cwdPath"
enabled = true
startup_timeout_sec = 30
tool_timeout_sec = 120

# [mcp_servers.$ServerName.env]
# MEDIA_MCP_DATA_PATH = "$dataPath"
"@
}

function Write-ConfigFile([string]$Path, [string]$Content) {
    $dir = Split-Path $Path -Parent
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    Set-Content -Path $Path -Value $Content -Encoding UTF8
    Write-Host "  Written: $Path" -ForegroundColor Green
}

function Write-Snippets([string]$Exe, [string]$Cwd) {
    New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
    $json = New-McpJson $Exe $Cwd
    Write-ConfigFile (Join-Path $ConfigDir 'mcp.json.snippet') $json
    Write-ConfigFile (Join-Path $ConfigDir 'claude_desktop_config.snippet.json') $json
    Write-ConfigFile (Join-Path $ConfigDir 'antigravity.mcp_config.snippet.json') $json
    Write-ConfigFile (Join-Path $ConfigDir 'windsurf.mcp_config.snippet.json') $json
    Write-ConfigFile (Join-Path $ConfigDir 'codex.config.snippet.toml') (New-CodexToml $Exe $Cwd)
    Write-Host "  Merge snippets into your client config (see docs\INSTALLATION.md)" -ForegroundColor Gray
}

Write-Host "=== Media MCP Server - Package Install ===" -ForegroundColor Cyan
Write-Host "Package: $PkgRoot"

Test-Package

foreach ($sub in @('captures', 'output', 'faces', 'video')) {
    New-Item -ItemType Directory -Force -Path (Join-Path $MediaDir $sub) | Out-Null
}

$exePath = (Resolve-Path $ExePath).Path
$binPath = (Resolve-Path $BinDir).Path
$mcpJson = New-McpJson $exePath $binPath
$codexToml = New-CodexToml $exePath $binPath

Write-Host ""
Write-Host "MCP executable: $exePath" -ForegroundColor Gray
Write-Host "Working dir:    $binPath" -ForegroundColor Gray

if ($Mode -eq 'cursor' -or $Mode -eq 'all') {
    Write-Host ""
    Write-Host "Cursor (project-level):" -ForegroundColor Cyan
    $cursorPath = Join-Path $PkgRoot '.cursor\mcp.json'
    Write-ConfigFile $cursorPath $mcpJson
    Write-Host "  Open this folder in Cursor, then Settings -> MCP -> Refresh"
}

if ($Mode -eq 'codex' -or $Mode -eq 'all') {
    Write-Host ""
    Write-Host "OpenAI Codex (project-level):" -ForegroundColor Cyan
    $codexPath = Join-Path $PkgRoot '.codex\config.toml'
    Write-ConfigFile $codexPath $codexToml
    Write-Host "  Trust this project in Codex, then run /mcp in a session"
}

if ($Mode -eq 'antigravity' -or $Mode -eq 'snippets' -or $Mode -eq 'all') {
    if ($Mode -eq 'antigravity') {
        Write-Host ""
        Write-Host "Google Antigravity:" -ForegroundColor Cyan
        Write-Host "  Config file: $env:USERPROFILE\.gemini\antigravity\mcp_config.json" -ForegroundColor Gray
        Write-Host "  Agent panel -> Manage MCP Servers -> View raw config" -ForegroundColor Gray
        Write-Host "  Add the media-mcp-server block from:" -ForegroundColor Gray
        $snippet = Join-Path $ConfigDir 'antigravity.mcp_config.snippet.json'
        Write-Snippets $exePath $binPath | Out-Null
        Write-Host "  $snippet" -ForegroundColor Green
    }
}

if ($Mode -eq 'windsurf' -or $Mode -eq 'snippets' -or $Mode -eq 'all') {
    if ($Mode -eq 'windsurf') {
        Write-Host ""
        Write-Host "Windsurf:" -ForegroundColor Cyan
        Write-Host "  Config file: $env:USERPROFILE\.codeium\windsurf\mcp_config.json" -ForegroundColor Gray
        Write-Host "  Cascade MCP hammer icon -> Configure" -ForegroundColor Gray
        $snippet = Join-Path $ConfigDir 'windsurf.mcp_config.snippet.json'
        Write-Snippets $exePath $binPath | Out-Null
        Write-Host "  Add block from: $snippet" -ForegroundColor Green
    }
}

if ($Mode -eq 'claude' -or $Mode -eq 'all') {
    Write-Host ""
    Write-Host "Claude Desktop:" -ForegroundColor Cyan
    $claudeDir = Join-Path $env:APPDATA 'Claude'
    $claudeCfg = Join-Path $claudeDir 'claude_desktop_config.json'
    if (Test-Path $claudeDir) {
        if (Test-Path $claudeCfg) {
            Write-Host "  Found existing config: $claudeCfg" -ForegroundColor Yellow
            Write-Host "  Merge manually - add media-mcp-server block" -ForegroundColor Yellow
            $example = Join-Path $ConfigDir 'claude_desktop_config.snippet.json'
            New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
            Write-ConfigFile $example $mcpJson
        } else {
            Write-ConfigFile $claudeCfg $mcpJson
        }
    } else {
        Write-Host "  Claude Desktop not found at $claudeDir" -ForegroundColor Yellow
        $example = Join-Path $ConfigDir 'claude_desktop_config.snippet.json'
        New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
        Write-ConfigFile $example $mcpJson
    }
}

if ($Mode -eq 'snippets' -or $Mode -eq 'all') {
    Write-Host ""
    Write-Host "Config snippets (all clients):" -ForegroundColor Cyan
    Write-Snippets $exePath $binPath
}

if ($Mode -eq 'print') {
    Write-Host ""
    Write-Host "JSON (Cursor / Antigravity / Windsurf / Claude):" -ForegroundColor Cyan
    Write-Host $mcpJson
    Write-Host ""
    Write-Host "TOML (Codex):" -ForegroundColor Cyan
    Write-Host $codexToml
    Write-Host ""
    Write-Host "Or run directly:" -ForegroundColor Cyan
    Write-Host "  cd `"$BinDir`""
    Write-Host "  .\MediaMCPServer.exe"
}

Write-Host ""
Write-Host "Environment (optional):" -ForegroundColor Cyan
Write-Host "  MEDIA_MCP_DATA_PATH = custom data folder"
Write-Host "  OPENCV_MODELS_PATH  = custom models folder"
Write-Host ""
Write-Host "See docs\INSTALLATION.md for per-client setup details." -ForegroundColor Cyan
Write-Host "Install complete." -ForegroundColor Green
