param(
    [string]$ServerName = 'media-mcp-server',
    [int]$Port = 8765,
    [string]$Path = '/mcp',
    [ValidateSet('auto', 'localhost', 'lan')]
    [string]$Bind = 'auto',
    [switch]$StartServer,
    [switch]$WriteSnippets
)

$ErrorActionPreference = "Stop"
$commonPath = Join-Path $PSScriptRoot '_common.ps1'
if (Test-Path $commonPath) {
    . $commonPath
} else {
    $script:ProjectRoot = Split-Path $PSScriptRoot -Parent
    $script:BinDir = Join-Path $ProjectRoot 'bin'
    $script:ConfigDir = Join-Path $ProjectRoot 'config'
}

$ExePath = Join-Path $BinDir 'MediaMCPServer.exe'
if (-not (Test-Path $ExePath)) {
    throw "Executable not found. Run install.ps1 first: $ExePath"
}

function Test-WslAvailable {
    try {
        $null = & wsl.exe -e true 2>$null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

function Get-WslWindowsHostIp {
    if (-not (Test-WslAvailable)) { return $null }
    try {
        $ip = (& wsl.exe -e bash -lc "grep -m1 '^nameserver ' /etc/resolv.conf 2>/dev/null | awk '{print `$2}'" 2>$null).Trim()
        if ($ip -match '^\d{1,3}(\.\d{1,3}){3}$') { return $ip }
    } catch { }
    return $null
}

function Test-WslMirroredNetworking {
    $wslConfig = Join-Path $env:USERPROFILE '.wslconfig'
    if (-not (Test-Path $wslConfig)) { return $false }
    $content = Get-Content $wslConfig -Raw -ErrorAction SilentlyContinue
    return ($content -match '(?mi)networkingMode\s*=\s*mirrored')
}

function Test-HttpEndpoint([string]$Url) {
    try {
        $body = '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{},"clientInfo":{"name":"wsl-setup","version":"1"}}}'
        $headers = @{
            'Accept' = 'application/json, text/event-stream'
            'Content-Type' = 'application/json'
        }
        $resp = Invoke-WebRequest -Uri $Url -Method POST -Headers $headers -Body $body -UseBasicParsing -TimeoutSec 5
        return $resp.StatusCode -eq 200
    } catch {
        return $false
    }
}

function New-HttpMcpJson([string]$Url) {
    @{
        mcpServers = @{
            $ServerName = @{
                url = $Url
            }
        }
    } | ConvertTo-Json -Depth 5
}

function New-CodexHttpToml([string]$Url) {
    @"
# Media MCP Server - WSL HTTP (generated by setup_wsl_http.ps1)
[mcp_servers.$ServerName]
url = "$Url"
enabled = true
startup_timeout_sec = 30
tool_timeout_sec = 120
"@
}

$wslAvailable = Test-WslAvailable
$mirrored = $false
$winHostIp = $null
if ($wslAvailable) {
    $mirrored = Test-WslMirroredNetworking
    $winHostIp = Get-WslWindowsHostIp
}

$bindHost = switch ($Bind) {
    'localhost' { '127.0.0.1' }
    'lan' { '0.0.0.0' }
    default {
        if ($mirrored) { '127.0.0.1' } else { '0.0.0.0' }
    }
}

$localhostUrl = "http://127.0.0.1:${Port}$Path"
$lanUrl = if ($winHostIp) { "http://${winHostIp}:${Port}$Path" } else { $null }

Write-Host ""
Write-Host "=== Media MCP Server - WSL HTTP setup ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Server bind (Windows): $bindHost`:$Port$Path" -ForegroundColor Gray

if (-not $wslAvailable) {
    Write-Warning "WSL not detected. Install WSL2 or run setup_wsl_mcp.sh from a Linux environment."
} else {
    if ($mirrored) {
        Write-Host "WSL networking: mirrored (127.0.0.1 usually works from WSL)" -ForegroundColor Green
    } else {
        Write-Host "WSL networking: NAT (use Windows host IP from WSL)" -ForegroundColor Yellow
        if ($winHostIp) {
            Write-Host "Windows host IP (from WSL resolv.conf): $winHostIp" -ForegroundColor Gray
        }
    }
}

$recommendedUrl = if ($mirrored -or -not $winHostIp) { $localhostUrl } else { $lanUrl }
Write-Host ""
Write-Host "Recommended MCP URL for WSL clients: $recommendedUrl" -ForegroundColor Green

if ($StartServer) {
    $listener = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
    if ($listener) {
        Write-Host "HTTP server already listening on port $Port" -ForegroundColor Yellow
    } else {
        $proc = Start-Process -FilePath $ExePath `
            -ArgumentList @('--host', $bindHost, '--port', $Port, '--path', $Path) `
            -WorkingDirectory $BinDir `
            -WindowStyle Hidden `
            -PassThru
        Start-Sleep -Seconds 2
        Write-Host "Started MediaMCPServer HTTP (PID $($proc.Id), bind $bindHost)" -ForegroundColor Green
    }
} else {
    Write-Host ""
    Write-Host "Start server on Windows:" -ForegroundColor Cyan
    if ($bindHost -eq '0.0.0.0') {
        Write-Host "  cd bin; .\launch_http_wsl.cmd" -ForegroundColor White
    } else {
        Write-Host "  cd bin; .\launch_http.cmd" -ForegroundColor White
    }
}

if (Test-HttpEndpoint $localhostUrl) {
    Write-Host "HTTP reachable from Windows: $localhostUrl" -ForegroundColor Green
} elseif (-not $StartServer) {
    Write-Host "HTTP not reachable yet (start the server first)" -ForegroundColor Yellow
}

if ($wslAvailable) {
    Write-Host ""
    Write-Host "Configure MCP inside WSL:" -ForegroundColor Cyan
    Write-Host "  bash scripts/setup_wsl_mcp.sh" -ForegroundColor White
    if ($winHostIp) {
        Write-Host "  bash scripts/setup_wsl_mcp.sh --host $winHostIp" -ForegroundColor White
    }
    Write-Host ""
    Write-Host "Test from WSL:" -ForegroundColor Cyan
    Write-Host "  bash scripts/tests/test_http_mcp_wsl.sh" -ForegroundColor White
}

if ($WriteSnippets) {
    New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
    $json = New-HttpMcpJson $recommendedUrl
    Set-Content -Path (Join-Path $ConfigDir 'mcp.wsl.http.json.snippet') -Value $json -Encoding UTF8
    Set-Content -Path (Join-Path $ConfigDir 'codex.http.wsl.config.snippet.toml') -Value (New-CodexHttpToml $recommendedUrl) -Encoding UTF8
    Write-Host ""
    Write-Host "Snippets written to config\mcp.wsl.http.json.snippet" -ForegroundColor Green
    Write-Host "Snippets written to config\codex.http.wsl.config.snippet.toml" -ForegroundColor Green
}

Write-Host ""
Write-Host "See docs/WSL.md for full WSL setup guide." -ForegroundColor Cyan
